#Copy the below content and paste it in the _config.yml file in your blog's root folder. This is necessary for the plugin to function properly.

# Blogroll
# The below value is used as the heading for your blogroll sidebar.
blogroll_name: Blogs I Read
# If the below is set to true, the latest feed will be retrieved using Google Feeds API and displayed on your sidebar.
# If you find setting this to true slows your blog too much, set it to false.
blogroll_show_latest_post: true
# If the below is set to true, jquery tinysort plugin will be used to sort your feeds in order of most recent update.
# Again, set this to false if you find your blog is slown down too much.
blogroll_enable_js_sort: true
# Since Google Feeds API takes time to update all the blogs in your blogroll, the above sorting should happen only after all feeds have been updated.
# The below variable controls the time (in milliseconds) after which the sorting algorithm should be fired.
# Note: This is applicable only if the above value is true.
blogroll_sort_timeout: 1500